spring:
  datasource:
    password: api_atlas@2026

atlas:
  encryption:
    secret-key: HEzRd71Vy82EHpkyzczNpJqf8efNxEwafQeE4KVVdw8=
  jwt:
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC04+d1bFCVQjMR
      AoMxPwBYQs1FUhddh3KDOs5mL80xpdhWsVV1cgwVaoB4DA7mgzzn++z4Amtw1iAv
      nAIN/mZbwngtgG29FHoVljU9LrLo0B/nwiBiPuYqlGFowr/AQzc7VrzId7LVq5zq
      ypwDfYmyGAL2weqNegxY0F31lPiR2YBCEpk42BLAabblYxxtI0lJdEOzj14oEhDg
      rJKxK2gQ1czO/QAt+/eg+33K4TrPKze0tB81Qy3pFn3tp+Lf3UnxdFgJweLtB8M2
      UJ0FeTP+ZozJVETXZFhA79nF6b7PcKQw9z9AIdHqgrvvZfTRDa4P22sl09M0wRTU
      BNRd/JXdAgMBAAECggEAF3PpAYdulzuDBXSO7+acM9VNaexvzRePmEYalpMiBorb
      FrpdOyHzQR+S0n21vNtNHULDgZBGv9VzTNjsR0YxnToEfNnG4Jn0DjJwaqNQXPEH
      AfRgYHyJOQIN8xg05keQtKfVSCSE0kEy0ho8yhMPtEB6ueWAdKFbUnSJihqrc7VI
      aqbUk56ZMT+qe0CxtT8m+pusLf+REyBk8aOIiNeuAsjYOGHqOzgtIcO1jsGlgbOh
      RKR+oX0rT7zGPgXWjw65UEjzeCkSNvpf+0NIYbmIy6XLfdczHWtFM9Zhcrj2lL6Y
      q4mHAAYd2IbXvBYaXmXelCsVIikTzoTXBu1h0grenQKBgQDsBp1n/t4XGzFDt+zS
      ekHNcTVXe6MrI4TEiluaow1S6AMH7QsCPtUyqu6y8AN6STvCz9WCsAM9OB635ePp
      4EWYNxbtEjDwNT2ZVSsk47ucWZWyIyDyUGlsoNK5ysv1Vd2YU/8dBTA4ef1RBxvE
      XIrEyfXYC02SX2w4UILeMTELJwKBgQDEMs2zyfRLXpLu6rj+eqxUp7CDQu1XiuE7
      w/+85uoGgM1gP08KKYcb6cMt5xeXJYVQyskfKD/yOwsOZ5Iu5qr+y72vYpDJQor0
      p1o0V8sS+8dE5HwkzdSMYv788Em0dEQ34GXf9ihJP7FOf6EJD/dT3aIMTWedIN+t
      EZSO8VTJWwKBgQDB5JU+r4MnHDGWXevw5HpWGSAm4+yhLaaOBtNF75iseOi0hCi9
      CXz/CKja2o0g0jSDz1So7YtbqVSi4fofURwa9Xah/oWxbytRYUP2JBclU/rDwlP4
      e9J/aIZ0FoMC4i0OTEKRRofcfWp6PAq1fwiIrRiHCJILItS2Vn2LpoGRlQKBgQCg
      YPcNdJSh15k8e9rlCto8CSec5OSmnvwmor02aXv7/OXlO1sc731mL9xAdZsvDpi/
      xkRJl9lN5T3QdJFmjWBSD7Hq4COCoUZ9Xx+5kdqKlg36HtvsKeUJLRNLKBDX1gK9
      uk0MmmesGMiTZnj4s3h1scJ5U/zS0MCG9Mv/XP716QKBgB5sk11vLKQJb2GNR/bn
      tgSIo7sN8fcaWR9/7VzdadE5rjcBnYwpoyDDz1Y1832TXD5SSA4y54sMbr/9J/hC
      7VVCzqAR8jZoaF5cZ8ECYbDCu9tH5gpZuFGWmp354BpHwF9zvT+gKLC90nG92lKp
      sJOB5kvCuO45J/vmuko+5kAH
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOPndWxQlUIzEQKDMT8A
      WELNRVIXXYdygzrOZi/NMaXYVrFVdXIMFWqAeAwO5oM85/vs+AJrcNYgL5wCDf5m
      W8J4LYBtvRR6FZY1PS6y6NAf58IgYj7mKpRhaMK/wEM3O1a8yHey1auc6sqcA32J
      shgC9sHqjXoMWNBd9ZT4kdmAQhKZONgSwGm25WMcbSNJSXRDs49eKBIQ4KySsSto
      ENXMzv0ALfv3oPt9yuE6zys3tLQfNUMt6RZ97afi391J8XRYCcHi7QfDNlCdBXkz
      /maMyVRE12RYQO/Zxem+z3CkMPc/QCHR6oK772X00Q2uD9trJdPTNMEU1ATUXfyV
      3QIDAQAB
      -----END PUBLIC KEY-----
    access-token-expiration: 1800
    refresh-token-expiration: 604800
